language: android
android:
  components:
    - tools
    - build-tools-26.0.2
    - platform-tools
    - android-26
    - tools
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_script:
  - chmod +x gradlew